### PR TITLE
fix(ws): Improve Workspace Creation Wizard Step Descriptions

### LINKED ISSUE #373: [TASK] Workspace Kind: Add More Context to Selection Step 1
Users need more information about what a "workspace kind" is and why it needs to be selected during workbench creation.

Image

**UX Recommendation**: Add an explanation of "workspace kind" and its purpose.

### PR DESCRIPTION
**Pull request by jenny-s51**
Closes #373 

## Description

This PR enhances the workspace creation wizard by providing more context for each step in the form flow.

Includes updated step descriptions for:
- **Kind Selection**
- **Image Selection**
- **Pod Config Selection** 

This enhancement improves the workspace creation process by helping users understand what to select and why each step matters for their workspace setup.

### CODE REVIEW

File: workspaces/frontend/src/app/pages/Workspaces/Form/WorkspaceForm.tsx [hunk 1]
```diff
@@ -30,10 +31,12 @@ enum WorkspaceFormSteps {
 }
 
 const stepDescriptions: { [key in WorkspaceFormSteps]?: string } = {
-  [WorkspaceFormSteps.KindSelection]: 'Select a workspace kind to use for the workspace.',
+  [WorkspaceFormSteps.KindSelection]:
+    'A workspace kind is a template that creates an isolated area where you can work with models in your preferred IDE, such as a Jupyter notebook.',
```
Comment (jiridanek) [inline workspaces/frontend/src/app/pages/Workspaces/Form/WorkspaceForm.tsx:35]: > your preferred IDE, such as a Jupyter notebook

this is not wrong, but I'd prefer to say "such as Jupyter Notebook" (leave out the a), or "such as JupyterLab". What do you all think?

File: workspaces/frontend/src/app/pages/Workspaces/Form/WorkspaceForm.tsx [hunk 2]
```diff
@@ -30,10 +31,12 @@ enum WorkspaceFormSteps {
...
   [WorkspaceFormSteps.ImageSelection]:
-    'Select a workspace image and image version to use for the workspace.',
-  [WorkspaceFormSteps.PodConfigSelection]: 'Select a pod config to use for the workspace.',
+    'Select a workspace image and image version to use for the workspace. A workspace image is a container image that contains the software and dependencies needed to run a workspace.',
+  [WorkspaceFormSteps.PodConfigSelection]:
+    'Select a pod config to use for the workspace. A pod config is a configuration that defines the resources and settings for a workspace pod.',
```
Comment (jiridanek) [inline workspaces/frontend/src/app/pages/Workspaces/Form/WorkspaceForm.tsx:39]: > for a workspace pod

maybe leave out _pod_?

**Review by jenny-s51 — COMMENTED** [review]
Thank you @jiridanek for your review! Appreciate your feedback, and these are great points. Updated to reflect your suggestions.

**Review by paulovmr — APPROVED** [review]
/lgtm
